itkdev_openid_connect:
    cache_options:
        cache_pool: 'cache.app' # Cache item pool for caching discovery document and CLI login tokens
    cli_login_options:
        route: '%env(CLI_REDIRECT)%' # Redirect route for CLI login
    openid_providers:
        # Define one or more providers
        # [providerKey]:
        #   options:
        #     metadata_url: …
        #     …
        oidc:
            options:
                metadata_url: '%env(OIDC_METADATA_URL)%'
                client_id: '%env(OIDC_CLIENT_ID)%'
                client_secret: '%env(OIDC_CLIENT_SECRET)%'
                # Specify redirect URI
                redirect_uri: '%env(OIDC_REDIRECT_URI)%'
                # Optional: Specify leeway (seconds) to account for clock skew between provider and hosting
                #           Defaults to 10
                # leeway: '%env(OIDC_LEEWAY)%'
