itkdev_openid_connect:
    cache_options:
        cache_pool: 'cache.app' # Cache item pool for caching discovery document and CLI login tokens
    cli_login_options:
        cli_redirect: '%env(CLI_REDIRECT)%' # Redirect route for CLI login
    openid_providers:
        # Define one or more providers
        # [providerKey]:
        #   options:
        #     metadata_url: …
        #     …
        admin:
            options:
                metadata_url: '%env(ADMIN_OIDC_METADATA_URL)%'
                client_id: '%env(ADMIN_OIDC_CLIENT_ID)%'
                client_secret: '%env(ADMIN_OIDC_CLIENT_SECRET)%'
                # Specify redirect URI
                redirect_uri: '%env(ADMIN_OIDC_REDIRECT_URI)%'
        user:
            options:
                metadata_url: '%env(USER_OIDC_METADATA_URL)%'
                client_id: '%env(USER_OIDC_CLIENT_ID)%'
                client_secret: '%env(USER_OIDC_CLIENT_SECRET)%'
                # As an alternative to using (a more or less) hardcoded redirect uri,
                # a Symfony route can be used as redirect URI
                redirect_route: 'default'
                # Define any params for the redirect_route
                # redirect_route_parameters: { type: user }