itkdev_openid_connect:
    cache_options:
        cache_pool: 'cache.app' # Cache item pool for caching discovery document and CLI login tokens
    cli_login_options:
        route: '%env(string:OIDC_CLI_REDIRECT)%' # Redirect route for CLI login
    user_provider: ~
    openid_providers:
        internal:
            options:
                metadata_url: '%env(string:INTERNAL_OIDC_METADATA_URL)%'
                client_id: '%env(string:INTERNAL_OIDC_CLIENT_ID)%'
                client_secret: '%env(string:INTERNAL_OIDC_CLIENT_SECRET)%'
                redirect_uri: '%env(string:INTERNAL_OIDC_REDIRECT_URI)%'
                leeway: '%env(int:INTERNAL_OIDC_LEEWAY)%'
        external:
            options:
                metadata_url: '%env(string:EXTERNAL_OIDC_METADATA_URL)%'
                client_id: '%env(string:EXTERNAL_OIDC_CLIENT_ID)%'
                client_secret: '%env(string:EXTERNAL_OIDC_CLIENT_SECRET)%'
                redirect_uri: '%env(string:EXTERNAL_OIDC_REDIRECT_URI)%'
                leeway: '%env(int:EXTERNAL_OIDC_LEEWAY)%'
