nelmio_cors:
    defaults:
        origin_regex: true
        allow_credentials: false
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'Authorization-Tenant-Key']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/v1/authentication/':
            allow_credentials: true
        '^/': null
