services:
  nginx:
    labels:
      # HTTPS config - uncomment to enable redirect from :80 to :443
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  redis:
    image: 'redis:6'
    networks:
      - app
    ports:
      - '6379'
