# itk-version: 1.0.0
version: "3"

networks:
  app:
    driver: bridge
    internal: false

services:
  phpfpm:
    image: itkdev/php8.0-fpm:alpine
    restart: unless-stopped
    networks:
      - app
    depends_on:
      - mariadb
    environment:
      - PHP_MAX_EXECUTION_TIME=30
      - PHP_MEMORY_LIMIT=128M
      - COMPOSER_VERSION=1
    volumes:
      - .:/app:delegated

  mariadb:
    image: itkdev/mariadb:latest
    networks:
      - app
    ports:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=db
      - MYSQL_PASSWORD=db
      - MYSQL_DATABASE=db
