# itk-version: 1.0.0
version: "3"

networks:
  frontend:
    external: true
  app:
    driver: bridge
    internal: false

services:
  mariadb:
    image: itkdev/mariadb:latest
    networks:
      - app
    ports:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=db
      - MYSQL_PASSWORD=db
      - MYSQL_DATABASE=db
      #- ENCRYPT=1 # Uncomment to enable database encryption.

  phpfpm:
    image: itkdev/php7.4-fpm:latest
    networks:
      - app
    environment:
      - XDEBUG_MODE=${XDEBUG_MODE:-off}
      - XDEBUG_SESSION=${XDEBUG_SESSION:-0}
      - PHP_MAX_EXECUTION_TIME=30
      - PHP_MEMORY_LIMIT=256M
      # - PHP_MAIL=1 # Uncomment to enable mailhog.
      - DOCKER_HOST_DOMAIN=${COMPOSE_DOMAIN}
      - COMPOSER_VERSION=2
      - PHP_IDE_CONFIG=serverName=localhost
    depends_on:
      - mariadb
    volumes:
      - .:/app:delegated

  nginx:
    image: nginx:latest
    networks:
      - app
      - frontend
    depends_on:
      - phpfpm
    ports:
      - "80"
    volumes:
      - ${PWD}/.docker/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/app:delegated
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_DOMAIN}`)"

  mailhog:
    image: mailhog/mailhog
    networks:
      - app
    ports:
      - "1025"
      - "8025"

  node:
    image: node:14
    command: npm start
    networks:
      - app
      - frontend
    working_dir: /app
    ports:
      - "3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ${PWD}/admin:/app:delegated

  cypress:
    image: cypress/included:7.7.0
    networks:
      - app
    depends_on:
      - nginx
    environment:
      - CYPRESS_VIDEO=true
      - CYPRESS_baseUrl=http://node:3000
    volumes:
      - ${PWD}/admin:/e2e
      - ${PWD}/admin:/app:delegated
      - /tmp/.X11-unix:/tmp/.X11-unix
    working_dir: /e2e
    entrypoint: cypress
