#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# api/config/routes.yaml
authentication_token:
  path: /v1/authentication_token
  methods: ['POST']

authentication-screen:
  path: /v1/authentication/screen
  methods: [ 'POST' ]
  controller: 'App\Controller\AuthScreenController'
