---
resources:
  App\Entity\ScreenLayout:
    attributes:
      #      input: App\Dto\MediaInput
      output: App\Dto\ScreenLayout
    itemOperations:
      get:
        path: '/layouts/{id}'
        openapi_context:
          description: Retrieves a screen layout resource.
          summary: Retrieve a screen layout resource.
          operationId: get-v1-layouts-id
          tags:
            - Layouts
          parameters:
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: id
              in: path
              required: true
          responses:
            '200':
              description: OK
              content:
                application/ld+json:
                  examples:
                    4-way-split:
                      value:
                        "@context": {
                          "@vocab": "http://displayapiservice.local.itkdev.dk/docs.jsonld#",
                          "hydra": "http://www.w3.org/ns/hydra/core#",
                          "title": "ScreenLayout/title",
                          "grid": "ScreenLayout/grid",
                          "regions": "ScreenLayout/regions"
                        },
                        '@type': "ScreenLayout"
                        '@id': /v1/layout/01FFMSXWE1KJ259DPR1HYKHSP6
                        title: 4 way split
                        grid:
                          rows: 2
                          columns: 2
                        regions:
                          - "@context": "/contexts/ScreenLayoutRegions"
                            "@id": "/v1/screen-layout-regions/01FFS94CHYW9268WFP1JF6H1VC"
                            "@type": "ScreenLayoutRegions"
                            title: Region 1
                            gridArea:
                              - a
                          - "@context": "/contexts/ScreenLayoutRegions"
                            "@id": "/v1/screen-layout-regions/01FFS94CHYW9268WFP1JF6H1VC"
                            "@type": "ScreenLayoutRegions"
                            title: Region 2
                            gridArea:
                              - b
                          - "@context": "/contexts/ScreenLayoutRegions"
                            "@id": "/v1/screen-layout-regions/01FFS94CHYW9268WFP1JF6H1VC"
                            "@type": "ScreenLayoutRegions"
                            title: Region 3
                            gridArea:
                              - c
                          - "@context": "/contexts/ScreenLayoutRegions"
                            "@id": "/v1/screen-layout-regions/01FFS94CHYW9268WFP1JF6H1VC"
                            "@type": "ScreenLayoutRegions"
                            title: Region 4
                            gridArea:
                              - d
                    Complicated:
                      value:
                        "@context": {
                          "@vocab": "http://displayapiservice.local.itkdev.dk/docs.jsonld#",
                          "hydra": "http://www.w3.org/ns/hydra/core#",
                          "title": "ScreenLayout/title",
                          "grid": "ScreenLayout/grid",
                          "regions": "ScreenLayout/regions"
                        },
                        '@type': "ScreenLayout"
                        '@id': /v1/layout/01FFMSXWE30CZKREE4E1C6DQ5J
                        title: 4 way split
                        grid:
                          rows: 4
                          columns: 12
                        regions:
                          - "@context": "/contexts/ScreenLayoutRegions"
                            "@id": "/v1/screen-layout-regions/01FFS94CHYW9268WFP1JF6H1VC"
                            "@type": "ScreenLayoutRegions"
                            title: Region 1
                            gridArea:
                              - a
                              - d
                          - "@context": "/contexts/ScreenLayoutRegions"
                            "@id": "/v1/screen-layout-regions/01FFS94CHYW9268WFP1JF6H1VC"
                            "@type": "ScreenLayoutRegions"
                            title: Region 2
                            gridArea:
                              - e
                              - m
                          - "@context": "/contexts/ScreenLayoutRegions"
                            "@id": "/v1/screen-layout-regions/01FFS94CHYW9268WFP1JF6H1VC"
                            "@type": "ScreenLayoutRegions"
                            title: Region 3
                            gridArea:
                              - q
                              - 'y'
                          - "@context": "/contexts/ScreenLayoutRegions"
                            "@id": "/v1/screen-layout-regions/01FFS94CHYW9268WFP1JF6H1VC"
                            "@type": "ScreenLayoutRegions"
                            title: Region 4
                            gridArea:
                              - cc
                              - oo
                          - "@context": "/contexts/ScreenLayoutRegions"
                            "@id": "/v1/screen-layout-regions/01FFS94CHYW9268WFP1JF6H1VC"
                            "@type": "ScreenLayoutRegions"
                            title: Region 5
                            gridArea:
                              - ss
                              - vv
                          - "@context": "/contexts/ScreenLayoutRegions"
                            "@id": "/v1/screen-layout-regions/01FFS94CHYW9268WFP1JF6H1VC"
                            "@type": "ScreenLayoutRegions"
                            title: Region 6
                            gridArea:
                              - f
                              - rr
                    3x3:
                      value:
                        "@context": {
                          "@vocab": "http://displayapiservice.local.itkdev.dk/docs.jsonld#",
                          "hydra": "http://www.w3.org/ns/hydra/core#",
                          "title": "ScreenLayout/title",
                          "grid": "ScreenLayout/grid",
                          "regions": "ScreenLayout/regions"
                        },
                        '@type': "ScreenLayout"
                        '@id': /v1/layout/01FFMSXWE6BGCBRH2M48ZZMHYR
                        title: 3x3
                        grid:
                          rows: 3
                          columns: 3
                        regions:
                          - "@context": "/contexts/ScreenLayoutRegions"
                            "@id": "/v1/screen-layout-regions/01FFS94CHYW9268WFP1JF6H1VC"
                            "@type": "ScreenLayoutRegions"
                            title: Region 1
                            gridArea:
                              - a
                          - "@context": "/contexts/ScreenLayoutRegions"
                            "@id": "/v1/screen-layout-regions/01FFS94CHYW9268WFP1JF6H1VC"
                            "@type": "ScreenLayoutRegions"
                            title: Region 2
                            gridArea:
                              - b
                          - "@context": "/contexts/ScreenLayoutRegions"
                            "@id": "/v1/screen-layout-regions/01FFS94CHYW9268WFP1JF6H1VC"
                            "@type": "ScreenLayoutRegions"
                            title: Region 3
                            gridArea:
                              - c
                          - "@context": "/contexts/ScreenLayoutRegions"
                            "@id": "/v1/screen-layout-regions/01FFS94CHYW9268WFP1JF6H1VC"
                            "@type": "ScreenLayoutRegions"
                            title: Region 4
                            gridArea:
                              - d
                          - "@context": "/contexts/ScreenLayoutRegions"
                            "@id": "/v1/screen-layout-regions/01FFS94CHYW9268WFP1JF6H1VC"
                            "@type": "ScreenLayoutRegions"
                            title: Region 5
                            gridArea:
                              - e
                          - "@context": "/contexts/ScreenLayoutRegions"
                            "@id": "/v1/screen-layout-regions/01FFS94CHYW9268WFP1JF6H1VC"
                            "@type": "ScreenLayoutRegions"
                            title: Region 6
                            gridArea:
                              - f
                          - "@context": "/contexts/ScreenLayoutRegions"
                            "@id": "/v1/screen-layout-regions/01FFS94CHYW9268WFP1JF6H1VC"
                            "@type": "ScreenLayoutRegions"
                            title: Region 7
                            gridArea:
                              - g
                          - "@context": "/contexts/ScreenLayoutRegions"
                            "@id": "/v1/screen-layout-regions/01FFS94CHYW9268WFP1JF6H1VC"
                            "@type": "ScreenLayoutRegions"
                            title: Region 8
                            gridArea:
                              - h
                          - "@context": "/contexts/ScreenLayoutRegions"
                            "@id": "/v1/screen-layout-regions/01FFS94CHYW9268WFP1JF6H1VC"
                            "@type": "ScreenLayoutRegions"
                            title: Region 9
                            gridArea:
                              - i
              headers: { }
#      put: ~
#      delete: ~

    collectionOperations:
      get:
        path: '/layouts'
        openapi_context:
          description: Retrieve a collection of layouts resources.
          summary: Retrieves a collection of layouts resources.
          tags:
            - Layouts
          operationId: get-v1-layouts
          parameters:
            - schema:
                type: integer
                minimum: 0
                format: int32
                default: 1
              in: query
              name: page
              required: true
            - schema:
                type: integer
                minimum: 0
                format: int32
                default: 10
              in: query
              name: itemsPerPage
              description: The number of items per page
          responses:
            '200':
              description: OK
              content:
                application/ld+json:
                  examples:

              headers: { }
#      post: ~
