---
resources:
  App\Api\Model\Media:
    itemOperations:
      get:
        path: '/v1/media/{id}'
        openapi_context:
          jsonld_context:
            '@id': http://yourcustomid.com,
            '@typ': http://www.w3.org/2001/XMLSchema#string,
          description: Retrieves a Media resource
          summary: Retrieve a Media resource
          operationId: get-v1-media-id
          tags:
            - Media
          parameters:
            - schema:
                type: string
                format: uuid
              name: id
              in: path
              required: true
          responses:
            '200':
              description: OK
              content:
                application/ld+json:
                  schema:
                    title: Media
                    type: object
                    properties:
                      '@id':
                        type: string
                      title:
                        type: string
                      description:
                        type: string
                      tags:
                        type: array
                        items:
                          type: string
                      modified:
                        format: time
                        type: integer
                      created:
                        type: integer
                      modifiedBy:
                        type: string
                      createdBy:
                        type: string
                      assets:
                        type: array
                        items:
                          type: object
                          properties:
                            type:
                              type: string
                            uri:
                              type: string
                              format: uri
                    required:
                      - '@id'
                      - title
                      - description
                      - tags
                      - modified
                      - created
                      - modifiedBy
                      - createdBy
                      - assets
                  examples:
                    Image:
                      value:
                        '@id': /v1/media/497f6eca-4576-4883-cfeb-53cbffba6f08
                        title: Sunset image
                        description: An image of a sunset
                        tags:
                          - itk
                          - example
                        modified: 1622556728
                        created: 1622550342
                        modifiedBy: Jens Jensen
                        createdBy: Ole Olesen
                        assets:
                          - type: image/png
                            uri: 'https://upload.wikimedia.org/wikipedia/commons/0/00/Sunset%2C_beach%2C_Northern_Territory_.png'
                    Video:
                      value:
                        '@id': /v1/media/597f6eca-4576-1454-cf15-52cb3eba6b85
                        title: Video
                        description: The bunny example movie
                        tags:
                          - itk
                          - mock
                        modified: 1622554784
                        created: 1622556728
                        modifiedBy: Ole Olesen
                        createdBy: Jens Jensen
                        assets:
                          - type: video/mp4
                            uri: 'https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4'
            '404':
              description: Not found
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      message:
                        type: string
                  examples:
                    '1':
                      value:
                        message: Not found
            '500':
              description: Internal error
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      message:
                        type: string
                  examples:
                    '1':
                      value:
                        message: Unknown internal application error
              headers: { }

    collectionOperations:
#      post: ~
      get:
        path: '/v1/media'

    properties:
      '@id':
         attributes:
           openapi_context:
             type: string
      title:
        attributes:
          openapi_context:
            type: string
      description:
        attributes:
          openapi_context:
            type: string
      tags:
        attributes:
          openapi_context:
            type: array
            items:
              type: string
      modified:
        attributes:
          openapi_context:
            format: time
            type: integer
      created:
        attributes:
          openapi_context:
            format: time
            type: integer
      modifiedBy:
        attributes:
          openapi_context:
            type: string
      createdBy:
        attributes:
          openapi_context:
            type: string
      assets:
        attributes:
          openapi_context:
            type: array
            items:
              type: object
              properties:
                type:
                  type: string
                uri:
                  type: string
                  format: uri
              attributes:
                input: false
