---
resources:
  App\Entity\PlaylistScreenRegion:
    attributes:
#      input: App\Dto\MediaInput
      output: App\Dto\Playlist
    itemOperations:

      delete:
        path: /screens/{ulid}/regions/{regionUlid}/playlists/{playlistUlid}
        openapi_context:
          tags:
            - Screens
          parameters:
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: ulid
              in: path
              required: true
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: regionUlid
              in: path
              required: true

      put:
        path: /screens/{ulid}/regions/{regionUlid}/playlists/{playlistUlid}
        openapi_context:
          tags:
            - Screens
          parameters:
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: ulid
              in: path
              required: true
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: regionUlid
              in: path
              required: true

    collectionOperations:
      get:
        controller: App\Controller\NotFoundAction
