---
resources:
  App\Entity\PlaylistSlide:
    attributes:
#      input: App\Dto\MediaInput
      output: App\Dto\PlaylistSlide
    itemOperations:
      get:
        # It needs to be here to generate id's in the collection lists.
        path: '/playlist-slides/{id}'
        controller: App\Controller\NotFoundAction

      delete:
        path: /poc/playlist/{id}/slides/{slideId}
        controller: App\Controller\PlaylistSlidePOCDeleteController
        read: false
        deserialize: false
        validate: false
        openapi_context:
          description: Delete a slide from a playlist.
          summary: Delete a slide from a playlist.
          operationId: delete-v1-playlist-id
          tags:
            - PlaylistSlide
          parameters:
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: id
              in: path
              required: true
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: slideId
              in: path
              required: true

      put:
        path: /poc/playlist/{id}/slides
        controller: App\Controller\PlaylistSlidePOCPutController
        read: false
        deserialize: false
        validate: false
        openapi_context:
          description: Update the collection of slide on a playlist.
          summary: Update the collection of slide on a playlist.
          operationId: put-v1-playlist-id
          tags:
            - PlaylistSlide
          requestBody:
            content:
              application/ld+json:
                schema:
                  type: array
                  items:
                    type: object
                    properties:
                      slide:
                        type: string
                        format: ulid
                        pattern: "^[A-Za-z0-9]{26}$"
                        description: Slide ULID
                      weight:
                        type: integer
          responses:
            '201':
              description: Created
              content:
                application/ld+json:
                  schema:
                    type: array
                    items:
                      type: object
                      properties:
                        slide:
                          type: string
                        playlist:
                          type: string
                        weight:
                          type: integer

    collectionOperations:
      get:
        path: /poc/playlist/{id}/slides
        controller: App\Controller\PlaylistSlidePOCGetController
        read: false
        deserialize: false
        validate: false
        openapi_context:
          description: Retrieves collection of weight Slide resources.
          summary: Retrieves collection of weight Slide resources.
          operationId: get-v1-playlistslide-id
          tags:
            - PlaylistSlide
          parameters:
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: id
              in: path
              required: true
            - schema:
                type: integer
                minimum: 0
                format: int32
                default: 1
              in: query
              name: page
              required: true
            - schema:
                type: string
                default: '10'
              in: query
              name: itemsPerPage
              description: The number of items per page
          responses:
            '200':
              description: OK
              content:
                application/ld+json:
                  examples:
              headers: { }
