---
resources:
  App\Entity\Playlist:
    attributes:
      output: App\Dto\Playlist
    itemOperations:
      get:
        openapi_context:
          operationId: get-v1-playlist-id
          description: Retrieve a Playlist resource.
          summary: Retrieves a Playlist resource.
          tags:
            - Playlist
          parameters:
            - schema:
                type: string
                format: uuid
              name: id
              in: path
              required: true
          responses:
            '200':
              description: OK
              content:
                application/ld+json:
                  examples:
              headers: { }

    collectionOperations:
#      post: ~
      get:
        openapi_context:
          operationId: get-v1-playlists
          description: Retrieves a collection of Playlist resources.
          summary: Retrieve a collection of Playlist resources.
          tags:
            - Playlist
          parameters:
            - schema:
                type: integer
                minimum: 0
                format: int32
                default: 1
              in: query
              name: page
              required: true
          responses:
            '200':
              description: OK
              content:
                application/ld+json:
                  examples:
              headers: { }
