---
resources:
  App\Entity\ScreenPlaylist:
    attributes:
      output: App\Dto\ScreenPlaylist
    itemOperations:
      get:
        # It needs to be here to generate id's in the collection lists.
        path: '/screen-playlists/{id}'
        controller: App\Controller\NotFoundAction

      delete:
        path: '/screens/{id}/playlists/{playlistId}'
        controller: App\Controller\ScreenPlaylistDeleteController
        read: false
        deserialize: false
        validate: false
        openapi_context:
          description: Delete a playlist from a playlist.
          summary: Delete a playlist from a playlist.
          operationId: delete-v1-screen-playlist-id
          tags:
            - Screens
          parameters:
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: id
              in: path
              required: true
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: playlistId
              in: path
              required: true

      put:
        path: '/screens/{id}/playlists'
        controller: App\Controller\ScreenPlaylistPutController
        read: false
        deserialize: false
        validate: false
        openapi_context:
          description: Update the collection of playlist on a screen.
          summary: Update the collection of playlist on a screen.
          operationId: put-v1-screen-playlist-id
          tags:
            - Screens
          requestBody:
            content:
              application/ld+json:
                schema:
                  type: array
                  items:
                    type: object
                    properties:
                      playlist:
                        type: string
                        format: ulid
                        pattern: "^[A-Za-z0-9]{26}$"
                        description: Playlist ULID

          responses:
            '201':
              description: Created
              content:
                application/ld+json:
                  schema:
                    type: array
                    items:
                      type: object
                      properties:
                        playlist:
                          type: string
                        screen:
                          type: string

    collectionOperations:
      get:
        filters: ['entity.search_filter', 'entity.published.date_filter', 'entity.order_filter', 'created.at.order_filter', 'updated.at.order_filter']
        path: '/screens/{id}/playlists'
        controller: App\Controller\ScreenPlaylistGetController
        read: false
        deserialize: false
        validate: false
        openapi_context:
          description: Retrieves collection of playlist resources.
          summary: Retrieves collection of playlist resources.
          operationId: get-v1-screen-playlist-id
          tags:
            - Screens
          parameters:
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: id
              in: path
              required: true
            - schema:
                type: integer
                minimum: 0
                format: int32
                default: 1
              in: query
              name: page
              required: true
            - schema:
                type: string
                default: '10'
              in: query
              name: itemsPerPage
              description: The number of items per page
          responses:
            '200':
              description: OK
              content:
                application/ld+json:
                  examples:
              headers: { }

