---
resources:
    App\Entity\ScreenLayoutRegions:
        attributes:
            output: App\Dto\ScreenLayoutRegions
            normalization_context:
                groups: ['read']
        itemOperations:
            get:
                path: '/layouts/regions/{id}'
                controller: App\Controller\NotFoundAction
        collectionOperations:
            get:
                path: '/layouts/regions'
                controller: App\Controller\NotFoundAction
