---
resources:
  App\Entity\ScreenLayoutRegions:
    attributes:
      #      input: App\Dto\MediaInput
      output: App\Dto\ScreenLayoutRegions
      normalization_context:
        groups: ['read']
    itemOperations:
      get:
        controller: ApiPlatform\Core\Action\NotFoundAction
        read: false
        output: false
#        path: '/layouts/{ulid}'
        openapi_context:
#          tags:
#            - Layouts
    collectionOperations:
