---
resources:
  App\Entity\Screen:
    itemOperations:
      get:
        path: '/v1/screen/{id}'
        openapi_context:
          operationId: get-screen
          description: Retrieves a Screen resource.
          summary: Retrieve a Screen resource.
          tags:
            - Screen
          parameters:
            - schema:
                type: string
                format: uuid
              name: id
              in: path
              required: true
          responses:
            '200':
              description: OK
              content:
                application/ld+json:
                  schema:
                    title: Screen
                    type: object
                    properties:
                      '@context':
                        type: string
                      '@id':
                        type: string
                      title:
                        type: string
                      description:
                        type: string
                      regions:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            playlists:
                              type: array
                              items:
                                type: string
                      tags:
                        type: array
                        items:
                          type: string
                      modified:
                        format: time
                        type: integer
                      created:
                        type: integer
                      modifiedBy:
                        type: string
                      createdBy:
                        type: string
                    required:
                      - '@id'
                      - title
                      - description
                      - regions
                      - tags
                      - modified
                      - created
                      - modifiedBy
                      - createdBy
                  examples:
                    Screen 1:
                      value:
                        '@id': /v1/screen/497f6eca-6276-1596-bfeb-53ceb43a6f54
                        title: Test screen 1
                        description: This is an test screen 1 description
                        regions:
                          - name: center
                            playlists:
                              - /v1/playlist/29ff6eca-8778-6789-bfeb-53e4bf4a6457
                        tags:
                          - itk
                          - screens
                          - test
                        modified: 1622535248
                        created: 1622524267
                        modifiedBy: Jens Jensen
                        createdBy: Ole Olesen
                    Screen 2:
                      value:
                        '@id': /v1/screen/854f6ecb-6276-6854-bfeb-53cffffa6d1e
                        title: Test screen 2
                        description: This is an test screen 2 description
                        regions:
                          - name: top
                            playlists:
                              - /v1/playlist/29ff6eca-8778-6789-bfeb-53e4bf4a6457
                          - name: buttom
                            playlists:
                              - /v1/playlist/29ff6eca-8778-6789-bfeb-53e4bf4a6457
                        tags:
                          - itk
                          - screens
                          - test
                        modified: 1622535248
                        created: 1622524267
                        modifiedBy: Jens Jensen
                        createdBy: Ole Olesen
            '404':
              description: Not found
              content:
                application/ld+json:
                  schema:
                    type: object
                    properties:
                      message:
                        type: string
                  examples:
                    '1':
                      value:
                        message: Not found
            '500':
              description: Internal error
              content:
                application/ld+json:
                  schema:
                    type: object
                    properties:
                      message:
                        type: string
                  examples:
                    '1':
                      value:
                        message: Unknown internal application error
              headers: { }

    collectionOperations:
#      post: ~
      get:
        path: '/v1/screens'
        openapi_context:
          operationId: get-v1-screens
          description: Retrieves a collection of Screen resources.
          summary: Retrieves a collection of Screen resources.
          tags:
            - Screen
          parameters:
            - schema:
                type: integer
                format: int32
                minimum: 0
                default: 1
              in: query
              name: page
              required: true
          responses:
            '200':
              description: OK
              content:
                application/ld+json:
                  schema:
                    type: object
                    properties:
                      '@id':
                        type: string
                        default: /v1/screens
                      '@type':
                        type: string
                        default: 'hydra:Collection'
                      'hydra:member':
                        type: array
                        items:
                          title: Screen
                          type: object
                          x-examples: { }
                          properties:
                            '@context':
                              type: string
                            '@id':
                              type: string
                            title:
                              type: string
                            description:
                              type: string
                            regions:
                              type: array
                              items:
                                type: object
                                properties:
                                  name:
                                    type: string
                                  playlists:
                                    type: array
                                    items:
                                      type: string
                            tags:
                              type: array
                              items:
                                type: string
                            modified:
                              format: time
                              type: integer
                            created:
                              type: integer
                            modifiedBy:
                              type: string
                            createdBy:
                              type: string
                          required:
                            - '@id'
                            - title
                            - description
                            - regions
                            - tags
                            - modified
                            - created
                            - modifiedBy
                            - createdBy
                      'hydra:totalItems':
                        type: integer
                      'hydra:view':
                        type: object
                        required:
                          - '@id'
                          - '@type'
                          - 'hydra:first'
                          - 'hydra:last'
                          - 'hydra:next'
                        properties:
                          '@id':
                            type: string
                          '@type':
                            type: string
                            default: 'hydra:PartialCollectionView'
                          'hydra:first':
                            type: string
                          'hydra:last':
                            type: string
                          'hydra:next':
                            type: string
                    required:
                      - '@id'
                      - '@type'
                      - 'hydra:member'
                      - 'hydra:totalItems'
                      - 'hydra:view'
                  examples:
                    Screens:
                      value:
                        '@id': /v1/screens
                        '@type': 'hydra:Collection'
                        'hydra:member':
                          - '@id': /v1/screen/497f6eca-6276-4993-bfeb-53cbffba6f58
                            title: Test screen 1
                            description: This is an test screen 1 description
                            regions:
                              - name: center
                                channels:
                                  - 497f6eca-6276-4993-bfeb-53cbbbba6d10
                                  - 497f6eca-6276-4993-bfeb-53cbaaba6f08
                            tags:
                              - itk
                              - screens
                              - test
                            modified: 1622535248
                            created: 1622524267
                            modifiedBy: Jens Jensen
                            createdBy: Ole Olesen
                          - '@id': /v1/screen/497f6eca-6276-4993-bfeb-53cbcbba6d12
                            title: Test screen 2
                            description: This is an test screen 2 description
                            regions:
                              - name: top
                                channels:
                                  - 497f6eca-6276-4993-bfeb-53cbbbba6d05
                              - name: buttom
                                channels:
                                  - 497f6eca-6276-4993-bfeb-53cbbbba6d11
                                  - 497f6eca-6276-4993-bfeb-53cbaaba6f12
                            tags:
                              - itk
                              - screens
                              - test
                            modified: 1622535248
                            created: 1622524267
                            modifiedBy: Jens Jensen
                            createdBy: Ole Olesen
                        'hydra:totalItems': 2
                        'hydra:view':
                          '@id': /v1/screens?page=1
                          '@type': 'hydra:PartialCollectionView'
                          'hydra:first': /v1/screens?page=1
                          'hydra:last': /v1/screens?page=1
                          'hydra:next': /v1/screens?page=1
            '404':
              description: Not found
              content:
                application/ld+json:
                  schema:
                    type: object
                    properties:
                      message:
                        type: string
                  examples:
                    '1':
                      value:
                        message: Not found
            '500':
              description: Internal error
              content:
                application/ld+json:
                  schema:
                    type: object
                    properties:
                      message:
                        type: string
                  examples:
                    '1':
                      value:
                        message: Unknown internal application error
              headers: { }

    properties:
      '@id':
         attributes:
           openapi_context:
             type: string
      title:
        attributes:
          openapi_context:
            type: string
      description:
        attributes:
          openapi_context:
            type: string
      tags:
        attributes:
          openapi_context:
            type: array
            items:
              type: string
      modified:
        attributes:
          openapi_context:
            format: time
            type: integer
      created:
        attributes:
          openapi_context:
            format: time
            type: integer
      modifiedBy:
        attributes:
          openapi_context:
            type: string
      createdBy:
        attributes:
          openapi_context:
            type: string
      regions:
        attributes:
          openapi_context:
            type: array
            items:
              type: object
              properties:
                name:
                  type: string
                playlists:
                  type: array
                  items:
                    type: string
