---
resources:
  App\Entity\ScreenGroup:
    attributes:
      input: App\Dto\ScreenGroupInput
      output: App\Dto\ScreenGroup
      denormalization_context:
        api_allow_update: true
    itemOperations:
      get:
        path: '/screenGroups/{id}'
        openapi_context:
          description: Retrieves a Screen group resource.
          summary: Retrieve a Screen group resource.
          operationId: get-v1-screen-groups-id
          tags:
            - ScreenGroups
          parameters:
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: id
              in: path
              required: true
          responses:
            '200':
              description: OK
              content:
                application/ld+json:
                  examples:
              headers: { }

      put:
        path: '/screenGroups/{id}'
        openapi_context:
          description: Update a Screen group resource.
          summary: Update a Screen group resource.
          operationId: put-v1-screen-groups-id
          tags:
            - ScreenGroups
          parameters:
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: id
              in: path
              required: true

      delete:
        path: '/screenGroups/{id}'
        openapi_context:
          description: Delete a Screen group resource.
          summary: Delete a Screen group resource.
          operationId: delete-v1-screen-groups-id
          tags:
            - ScreenGroups
          parameters:
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: id
              in: path
              required: true

      putRelateScreen:
        method: PUT
        path: '/screens/{id}/screenGroups'
        controller: App\Controller\ScreenGroupsScreensPutController
        read: false
        deserialize: false
        validate: false
        openapi_context:
          description: Update the collection of ScreenGroups on a Screen.
          summary: Update the collection of ScreenGroups on a Screen.
          operationId: put-v1-screen-groups-screen
          tags:
            - Screens
          parameters:
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: id
              in: path
              required: true
          requestBody:
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: string
          responses:
            '200':
              description: OK
              content:
                application/ld+json:
                  examples:

      deleteRelatedScreen:
        method: DELETE
        path: '/screens/{id}/screenGroups/{screenGroupId}'
        controller: App\Controller\ScreenGroupsScreensDeleteController
        read: false
        deserialize: false
        validate: false
        openapi_context:
          description: Delete a screen groups from a screen.
          summary: Delete a screen groups from a screen
          operationId: delete-v1-screen-group-screen-id
          tags:
            - Screens
          parameters:
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: id
              in: path
              required: true
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: screenGroupId
              in: path
              required: true

    collectionOperations:
      get:
        path: '/screenGroups'
        openapi_context:
          description: Retrieve a collection of Screen group resources.
          summary: Retrieves a collection of Screen group resources.
          tags:
            - ScreenGroups
          operationId: get-v1-screen-groups
          parameters:
            - schema:
                type: integer
                minimum: 0
                format: int32
                default: 1
              in: query
              name: page
            - schema:
                type: string
                default: '10'
              in: query
              name: itemsPerPage
              description: The number of items per page
          responses:
            '200':
              description: OK
              content:
                application/ld+json:
                  examples:
                    Groups:
                      value:
                        '@id': /v1/screenGroups
                        '@type': 'hydra:Collection'
                        'hydra:member':
                          - "@type": "ScreenGroup"
                            "@id": "/v1/screen-groups/01FFS94CJXKT2JBWEMTDP0JNFK"
                            "title": "Voluptas blanditiis non tempora cupiditate unde."
                            "description": "Eos ea et modi impedit non quod. Ipsa ut et aut quis velit sit occaecati dolorem. Ut et quidem rerum aut ducimus nihil."
                            "created": "2021-09-17T07:04:33+02:00"
                            "modified": "2021-09-17T07:04:33+02:00"
                            "modifiedBy": ""
                            "createdBy": ""
                          - "@type": "ScreenGroup"
                            "@id": "/v1/screen-groups/01FFS94CK0TJN47KXMZ2FYEAH8"
                            "title": "Qui perspiciatis et autem repellendus."
                            "description": "Dolor est eius officiis et. Et alias nemo rerum modi repellendus ipsa. Dolores nesciunt qui et et ratione."
                            "created": "2021-09-17T07:04:33+02:00"
                            "modified": "2021-09-17T07:04:33+02:00"
                            "modifiedBy": ""
                            "createdBy": ""
                        'hydra:totalItems': 2
                        'hydra:view':
                          '@id': string
                          '@type': 'hydra:PartialCollectionView'
                          'hydra:first': string
                          'hydra:last': string
                          'hydra:next': string
              headers: { }

      getBaseOnRegion:
        method: GET
        path: /screens/{id}/screenGroups
        controller: App\Controller\ScreenGroupsScreensGetController
        read: false
        openapi_context:
          operationId: get-v1-screen-id-screen-groups
          description: Retrieve ScreeGroups collection base on screen id.
          summary: Retrieve ScreeGroups collection base on screen id.
          tags:
            - Screens
          parameters:
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: id
              in: path
              required: true
            - schema:
                type: integer
                minimum: 0
                format: int32
                default: 1
              in: query
              name: page
              required: true
            - schema:
                type: string
                default: '10'
              in: query
              name: itemsPerPage
              description: The number of items per page

      post:
        path: '/screenGroups'
        openapi_context:
          description: Create Screen group resources.
          summary: Create Screen group resources.
          operationId: post-v1-screen-groups
          tags:
            - ScreenGroups
