---
resources:
  App\Entity\Screen:
    attributes:
      output: App\Dto\Screen
    itemOperations:
      get:
        openapi_context:
          operationId: get-screens-id
          description: Retrieves a Screen resource.
          summary: Retrieve a Screen resource.
          tags:
            - Screen
          parameters:
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: ulid
              in: path
              required: true
          responses:
            '200':
              description: OK
              content:
                application/ld+json:

              headers: { }

    collectionOperations:
      get:
        openapi_context:
          operationId: get-v1-screens
          description: Retrieves a collection of Screen resources.
          summary: Retrieves a collection of Screen resources.
          tags:
            - Screen
          parameters:
            - schema:
                type: integer
                minimum: 0
                format: int32
                default: 1
              in: query
              name: page
              required: true
            - schema:
                type: string
                default: '10'
              in: query
              name: itemsPerPage
              description: The number of items per page
          responses:
            '200':
              description: OK
              content:
                application/ld+json:
                  examples:

              headers: { }
