---
resources:
  App\Entity\ScreenLayoutRegions:
    attributes:
      output: App\Dto\ScreenLayoutRegions
      normalization_context:
        groups: ['read']
    itemOperations:
      get:
        controller: App\Controller\NotFoundAction
    collectionOperations:
      get:
        controller: App\Controller\NotFoundAction

