---
resources:
  App\Entity\Screen:
    properties:
      screenLayout:
        subresource:
          resourceClass: 'App\Entity\ScreenLayout'
          path: '/layouts/{ulid}'
          collection: false
    attributes:
      output: App\Dto\Screen
    itemOperations:
      get:
#        openapi_context:
#          operationId: get-screens-id
#          description: Retrieves a Screen resource.
#          summary: Retrieve a Screen resource.
#          tags:
#            - Screen
#          parameters:
#            - schema:
#                type: string
#                format: ulid
#                pattern: "^[A-Za-z0-9]{26}$"
#              name: ulid
#              in: path
#              required: true
#          responses:
#            '200':
#              description: OK
#              content:
#                application/ld+json:
#                  examples:
#                    Screen 1:
#                      value:
#                        '@id': /v1/screen/497f6eca-6276-1596-bfeb-53ceb43a6f54
#                        title: Test screen 1
#                        description: This is an test screen 1 description
#                        regions:
#                          - name: center
#                            playlists:
#                              - /v1/playlist/29ff6eca-8778-6789-bfeb-53e4bf4a6457
#                        tags:
#                          - itk
#                          - screens
#                          - test
#                        modified: 1622535248
#                        created: 1622524267
#                        modifiedBy: Jens Jensen
#                        createdBy: Ole Olesen
#                    Screen 2:
#                      value:
#                        '@id': /v1/screen/854f6ecb-6276-6854-bfeb-53cffffa6d1e
#                        title: Test screen 2
#                        description: This is an test screen 2 description
#                        regions:
#                          - name: top
#                            playlists:
#                              - /v1/playlist/29ff6eca-8778-6789-bfeb-53e4bf4a6457
#                          - name: buttom
#                            playlists:
#                              - /v1/playlist/29ff6eca-8778-6789-bfeb-53e4bf4a6457
#                        tags:
#                          - itk
#                          - screens
#                          - test
#                        modified: 1622535248
#                        created: 1622524267
#                        modifiedBy: Jens Jensen
#                        createdBy: Ole Olesen
#              headers: { }

    collectionOperations:
      get:
#        openapi_context:
#          operationId: get-v1-screens
#          description: Retrieves a collection of Screen resources.
#          summary: Retrieves a collection of Screen resources.
#          tags:
#            - Screen
#          parameters:
#            - schema:
#                type: integer
#                minimum: 0
#                format: int32
#                default: 1
#              in: query
#              name: page
#              required: true
#            - schema:
#                type: string
#                default: '10'
#              in: query
#              name: itemsPerPage
#              description: The number of items per page
#          responses:
#            '200':
#              description: OK
#              content:
#                application/ld+json:
#                  examples:
#                    Screens:
#                      value:
#                        '@id': /v1/screens
#                        '@type': 'hydra:Collection'
#                        'hydra:member':
#                          - '@id': /v1/screen/497f6eca-6276-4993-bfeb-53cbffba6f58
#                            title: Test screen 1
#                            description: This is an test screen 1 description
#                            regions:
#                              - name: center
#                                channels:
#                                  - 497f6eca-6276-4993-bfeb-53cbbbba6d10
#                                  - 497f6eca-6276-4993-bfeb-53cbaaba6f08
#                            modified: 1622535248
#                            created: 1622524267
#                            modifiedBy: Jens Jensen
#                            createdBy: Ole Olesen
#                          - '@id': /v1/screen/497f6eca-6276-4993-bfeb-53cbcbba6d12
#                            title: Test screen 2
#                            description: This is an test screen 2 description
#                            regions:
#                              - name: top
#                                channels:
#                                  - 497f6eca-6276-4993-bfeb-53cbbbba6d05
#                              - name: buttom
#                                channels:
#                                  - 497f6eca-6276-4993-bfeb-53cbbbba6d11
#                                  - 497f6eca-6276-4993-bfeb-53cbaaba6f12
#                            modified: 1622535248
#                            created: 1622524267
#                            modifiedBy: Jens Jensen
#                            createdBy: Ole Olesen
#                        'hydra:totalItems': 2
#                        'hydra:view':
#                          '@id': /v1/screens?page=1
#                          '@type': 'hydra:PartialCollectionView'
#                          'hydra:first': /v1/screens?page=1
#                          'hydra:last': /v1/screens?page=1
#                          'hydra:next': /v1/screens?page=1
#              headers: { }
