---
resources:
  App\Entity\Slide:
    attributes:
      #      input: App\Dto\MediaInput
      output: App\Dto\Slide
    itemOperations:
      get:
        openapi_context:
          operationId: get-v1-slide-id
          description: Retrieves a Slide resource.
          summary: Retrieve a Slide resource.
          tags:
            - Slides
          parameters:
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: id
              in: path
              required: true
          responses:
            '200':
              description: OK
              content:
                application/ld+json:
                  examples:
              headers: { }

    collectionOperations:
#      post: ~
      get:
        openapi_context:
          operationId: get-v1-slides
          description: Retrieves a collection of Slide resources.
          summary: Retrieves a collection of Slide resources.
          tags:
            - Slides
          parameters:
            - schema:
                type: integer
                minimum: 0
                format: int32
                default: 1
              in: query
              name: page
              required: true
            - schema:
                type: string
                default: '10'
              in: query
              name: itemsPerPage
              description: The number of items per page
          responses:
            '200':
              description: OK
              content:
                application/ld+json:
                  examples:
              headers: {}


