---
resources:
  App\Entity\Slide:
    itemOperations:
      get:
        path: '/v1/slide/{id}'
        openapi_context:
          operationId: get-v1-slide-id
          description: Retrieves a Slide resource.
          summary: Retrieve a Slide resource.
          tags:
            - Slide
          parameters:
            - schema:
                type: string
                format: uuid
              name: id
              in: path
              required: true
          responses:
            '200':
              description: OK
              content:
                application/ld+json:
                  schema:
                    title: Slide v1
                    type: object
                    description: ''
                    properties:
                      '@context':
                        type: string
                      '@id':
                        type: string
                      title:
                        type: string
                      description:
                        type: string
                      tags:
                        type: array
                        items:
                          type: string
                      modified:
                        format: time
                        type: integer
                      created:
                        type: integer
                      modifiedBy:
                        type: string
                      createdBy:
                        type: string
                      template:
                        type: object
                        required:
                          - '@id'
                          - options
                        properties:
                          '@id':
                            type: string
                          options:
                            type: array
                            items:
                              type: object
                      duration:
                        type: integer
                        minimum: 0
                      content:
                        type: object
                      published:
                        type: integer
                        default: 0
                    required:
                      - '@id'
                      - title
                      - description
                      - tags
                      - modified
                      - created
                      - modifiedBy
                      - createdBy
                      - template
                      - duration
                      - content
                      - published
                  examples:
                    Slide image:
                      value:
                        '@context': /contexts/Slide
                        '@id': /v1/slide/a97f6ec4-5278-4993-bfeb-53cdedea6d10
                        title: Image Slide
                        description: This is the first slide named one
                        tags:
                          - itk
                          - mock
                          - example
                        modified: 1622555123
                        created: 1622554031
                        modifiedBy: Ole Olesen
                        createdBy: Jens Jensen
                        template:
                          '@id': /v1/template/457d6ecb-6378-4299-bfcb-53cbaaaa6f65
                          options:
                            - fade: false
                            - icon: true
                              url: 'http://test.local.itkdev.dk/icon.png'
                        duration: 45
                        content:
                          text: This is slide content
                          media: /v1/media/497f6eca-4576-4883-cfeb-53cbffba6f08
                        published: 1
                    Slide video:
                      value:
                        '@context': /contexts/Slide
                        '@id': /v1/slide/787f6ece-6276-5982-beeb-53cba4f36f12
                        title: Video Slide
                        description: This is the next slide named two
                        tags:
                          - itk
                          - mock
                          - example
                        modified: 1622555475
                        created: 1622553404
                        modifiedBy: Jens Jensen
                        createdBy: Ole Olesen
                        template:
                          '@id': /v1/template/457d6ecb-6378-4299-bfcb-53cbaaaa6f65
                          options:
                            - fade: true
                        duration: 90
                        content:
                          media: /v1/media/597f6eca-4576-1454-cf15-52cb3eba6b85
                        published: 1
            '404':
              description: Not found
              content:
                application/ld+json:
                  schema:
                    type: object
                    properties:
                      message:
                        type: string
                  examples:
                    '1':
                      value:
                        message: Not found
            '500':
              description: Internal error
              content:
                application/ld+json:
                  schema:
                    type: object
                    properties:
                      message:
                        type: string
                  examples:
                    '1':
                      value:
                        message: Unknown internal application error
              headers: { }

    collectionOperations:
#      post: ~
      get:
        path: '/v1/slides'
        openapi_context:
          operationId: get-v1-slides
          description: Retrieves a collection of Slide resources.
          summary: Retrieves a collection of Slide resources.
          tags:
            - Slide
          parameters:
            - schema:
                type: integer
                minimum: 0
                format: int32
                default: 1
              in: query
              name: page
              required: true
          responses:
            '200':
              description: OK
              content:
                application/ld+json:
                  schema:
                    type: object
                    properties:
                      '@id':
                        type: string
                        default: /v1/slides
                      '@type':
                        type: string
                        default: 'hydra:Collection'
                      'hydra:member':
                        type: array
                        items:
                          title: Slide v1
                          type: object
                          x-examples: {}
                          description: ''
                          properties:
                            '@context':
                              type: string
                            '@id':
                              type: string
                            title:
                              type: string
                            description:
                              type: string
                            tags:
                              type: array
                              items:
                                type: string
                            modified:
                              format: time
                              type: integer
                            created:
                              type: integer
                            modifiedBy:
                              type: string
                            createdBy:
                              type: string
                            template:
                              type: object
                              required:
                                - '@id'
                                - options
                              properties:
                                '@id':
                                  type: string
                                options:
                                  type: array
                                  items:
                                    type: object
                            duration:
                              type: integer
                              minimum: 0
                            content:
                              type: object
                            published:
                              type: integer
                              default: 0
                          required:
                            - '@id'
                            - title
                            - description
                            - tags
                            - modified
                            - created
                            - modifiedBy
                            - createdBy
                            - template
                            - duration
                            - content
                            - published
                      'hydra:totalItems':
                        type: integer
                      'hydra:view':
                        type: object
                        properties:
                          '@id':
                            type: string
                          '@type':
                            type: string
                            default: 'hydra:PartialCollectionView'
                          'hydra:first':
                            type: string
                          'hydra:last':
                            type: string
                          'hydra:next':
                            type: string
                  examples:
                    Slides:
                      value:
                        '@id': /v1/slides
                        '@type': 'hydra:Collection'
                        'hydra:member':
                          - '@id': /v1/slide/a97f6ec4-5278-4993-bfeb-53cdedea6d10
                            title: Image Slide
                            description: This is the first slide named one
                            tags:
                              - itk
                              - mock
                              - example
                            modified: 1622555123
                            created: 1622554031
                            modifiedBy: Ole Olesen
                            createdBy: Jens Jensen
                            template:
                              '@id': /v1/template/457d6ecb-6378-4299-bfcb-53cbaaaa6f65
                              options:
                                - fade: false
                                - icon: true
                                  url: 'http://test.local.itkdev.dk/icon.png'
                            duration: 45
                            content:
                              text: This is slide content
                              media: 497f6eca-4576-4883-cfeb-53cbffba6f08
                            published: 1
                          - '@id': /v1/slide/787f6ece-6276-5982-beeb-53cba4f36f12
                            title: Video Slide
                            description: This is the next slide named two
                            tags:
                              - itk
                              - mock
                              - example
                            modified: 1622555475
                            created: 1622553404
                            modifiedBy: Jens Jensen
                            createdBy: Ole Olesen
                            template:
                              '@id': /v1/template/457d6ecb-6378-4299-bfcb-53cbaaaa6f65
                              options:
                                - fade: true
                            duration: 90
                            content:
                              media: 597f6eca-4576-1454-cf15-52cb3eba6b85
                            published: 1
                        'hydra:totalItems': 2
                        'hydra:view':
                          '@id': /v1/slides?page=1
                          '@type': 'hydra:PartialCollectionView'
                          'hydra:first': /v1/slides?page=1
                          'hydra:last': /v1/slides?page=1
                          'hydra:next': /v1/slides?page=1
            '404':
              description: Not found
              content:
                application/ld+json:
                  schema:
                    type: object
                    properties:
                      message:
                        type: string
                  examples:
                    '1':
                      value:
                        message: Not found
            '500':
              description: Internal error
              content:
                application/ld+json:
                  schema:
                    type: object
                    properties:
                      message:
                        type: string
                  examples:
                    '1':
                      value:
                        message: Unknown internal application error
              headers: {}

    properties:
      '@id':
         attributes:
           openapi_context:
             type: string
      title:
        attributes:
          openapi_context:
            type: string
      description:
        attributes:
          openapi_context:
            type: string
      tags:
        attributes:
          openapi_context:
            type: array
            items:
              type: string
      modified:
        attributes:
          openapi_context:
            format: time
            type: integer
      created:
        attributes:
          openapi_context:
            format: time
            type: integer
      modifiedBy:
        attributes:
          openapi_context:
            type: string
      createdBy:
        attributes:
          openapi_context:
            type: string
      template:
        attributes:
          openapi_context:
            type: object
            required:
              - '@id'
              - options
            properties:
              '@id':
                type: string
              options:
                type: array
                items:
                  type: object
        duration:
          attributes:
            openapi_context:
              type: integer
              minimum: 0
        content:
          attributes:
            openapi_context:
              type: object
        published:
          attributes:
            openapi_context:
              type: integer
              default: 0

