---
resources:
  App\Entity\Slide:
    attributes:
      #      input: App\Dto\MediaInput
      output: App\Dto\Slide
    itemOperations:
      get:
        openapi_context:
          operationId: get-v1-slide-id
          description: Retrieves a Slide resource.
          summary: Retrieve a Slide resource.
          tags:
            - Slide
          parameters:
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: ulid
              in: path
              required: true
          responses:
            '200':
              description: OK
              content:
                application/ld+json:
                  examples:
              headers: { }

    collectionOperations:
#      post: ~
      get:
        openapi_context:
          operationId: get-v1-slides
          description: Retrieves a collection of Slide resources.
          summary: Retrieves a collection of Slide resources.
          tags:
            - Slide
          parameters:
            - schema:
                type: integer
                minimum: 0
                format: int32
                default: 1
              in: query
              name: page
              required: true
            - schema:
                type: string
                default: '10'
              in: query
              name: itemsPerPage
              description: The number of items per page
          responses:
            '200':
              description: OK
              content:
                application/ld+json:
                  examples:
              headers: {}

    properties:
      '@id':
         attributes:
           openapi_context:
             type: string
      title:
        attributes:
          openapi_context:
            type: string
      description:
        attributes:
          openapi_context:
            type: string
      tags:
        attributes:
          openapi_context:
            type: array
            items:
              type: string
      modified:
        attributes:
          openapi_context:
            format: time
            type: integer
      created:
        attributes:
          openapi_context:
            format: time
            type: integer
      modifiedBy:
        attributes:
          openapi_context:
            type: string
      createdBy:
        attributes:
          openapi_context:
            type: string
      template:
        attributes:
          openapi_context:
            type: object
            required:
              - '@id'
              - options
            properties:
              '@id':
                type: string
              options:
                type: array
                items:
                  type: object
        duration:
          attributes:
            openapi_context:
              type: integer
              minimum: 0
        content:
          attributes:
            openapi_context:
              type: object
        published:
          attributes:
            openapi_context:
              type: integer
              default: 0

