---
resources:
  App\Entity\Template:
    attributes:
      #      input: App\Dto\MediaInput
      output: App\Dto\Template
    itemOperations:
      get:
        openapi_context:
          description: Retrieves a Template resource.
          summary: Retrieve a Template resource.
          operationId: get-v1-template-id
          tags:
            - Templates
          parameters:
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: id
              in: path
              required: true
          responses:
            '200':
              description: OK
              content:
                application/ld+json:
                  examples:
              headers: { }

    collectionOperations:
      get:
        openapi_context:
          operationId: get-v1-templates
          description:  Retrieve a collection of Template resources.
          summary:  Retrieve a collection of Template resources.
          tags:
            - Templates
          parameters:
            - schema:
                type: integer
                minimum: 0
                format: int32
                default: 1
              in: query
              name: page
            - schema:
                type: string
                default: '10'
              in: query
              name: itemsPerPage
              description: The number of items per page
          responses:
            '200':
              description: OK
              content:
                application/ld+json:
                  examples:
              headers: { }
