---
resources:
  App\Entity\Tenant:
    attributes:
      normalization_context:
        datetime_format: 'Y-m-d\TH:i:s.v\Z'
    collectionOperations:
      get:
        filters: ['entity.search_filter']
        openapi_context:
          operationId: get-v1-tenants
          description: Retrieves a collection of tenant resources.
          summary: Retrieves a collection of tenant resources.
          tags:
            - Tenants
          parameters:
            - schema:
                type: integer
                minimum: 0
                format: int32
                default: 1
              in: query
              name: page
            - schema:
                type: string
                default: '10'
              in: query
              name: itemsPerPage
              description: The number of items per page
          responses:
            '200':
              description: OK
              content:
                application/ld+json:
                  examples:
              headers: {}

