---
resources:
  App\Entity\Theme:
    attributes:
      output: App\Dto\Theme
    itemOperations:
      get:
        openapi_context:
          description: Retrieves a Theme resource.
          summary: Retrieve a Theme resource.
          operationId: get-v1-theme-id
          tags:
            - Themes
          parameters:
            - schema:
                type: string
                format: ulid
                pattern: "^[A-Za-z0-9]{26}$"
              name: id
              in: path
              required: true
          responses:
            '200':
              description: OK
              content:
                application/ld+json:
                  examples:
              headers: { }

    collectionOperations:
      get:
        filters: ['entity.search_filter', 'created.at.order_filter', 'updated.at.order_filter']
        openapi_context:
          operationId: get-v1-themes
          description:  Retrieve a collection of Theme resources.
          summary:  Retrieve a collection of Theme resources.
          tags:
            - Themes
          parameters:
            - schema:
                type: integer
                minimum: 0
                format: int32
                default: 1
              in: query
              name: page
            - schema:
                type: string
                default: '10'
              in: query
              name: itemsPerPage
              description: The number of items per page
          responses:
            '200':
              description: OK
              content:
                application/ld+json:
                  examples:
              headers: { }
