---
resources:
    App\Entity\Tenant\UserActivationCode:
        #provider: App\State\MediaProvider
        processor: App\State\UserActivationCodeProvider

        itemOperations:
            ApiPlatform\Metadata\Get: &get:
                security: is_granted("ROLE_EXTERNAL_USER_ADMIN")
            ApiPlatform\Metadata\Delete: &delete:
                security: is_granted("ROLE_EXTERNAL_USER_ADMIN")
            refresh_code:
                class: ApiPlatform\Metadata\Post
                method: POST
                uriTemplate: /user-activation-codes/{id}/refresh-code
                security: is_granted("ROLE_EXTERNAL_USER_ADMIN")
                controller: App\Controller\UserRefreshCodeController
                input: App\Dto\EmptyDTO
                openapi_context:
                    description: Refresh user activation code.
                    summary: Refresh user activation code.
                    operationId: post-v1-refresh-user-activation-code
                    tags:
                        - UserActivationCode
                    parameters:
                        -   schema:
                                type: string
                                format: ulid
                                pattern: "^[A-Za-z0-9]{26}$"
                            name: id
                            in: path
                            required: true
                    responses:
                        '201': ~
                        '204':
                            description: Activation code was refreshed
                            content:
                                application/ld+json:
                                    examples:
                            headers: { }

            ApiPlatform\Metadata\GetCollection:
                security: is_granted("ROLE_EXTERNAL_USER_ADMIN")
            ApiPlatform\Metadata\Post: &post
                security: is_granted("ROLE_EXTERNAL_USER_ADMIN")
                input: App\Dto\UserActivationCodeInput
                openapi_context:
                    description: Create user activation code
                    summary: Create user activation code.
                    operationId: post-v1-create-user-activation-code
                    tags:
                        - UserActivationCode
            activate:
                class: ApiPlatform\Metadata\Post
                method: POST
                uriTemplate: /user-activation-codes/activate
                security: is_granted("ROLE_USER")
                controller: App\Controller\UserActivateController
                input: App\Dto\UserActivateInput
                openapi_context:
                    description: Use user activation code.
                    summary: Use user activation code.
                    operationId: post-v1-activate-user-activation-code
                    tags:
                        - UserActivationCode
                    parameters:
                    responses:
                        '201': ~
                        '204':
                            description: Activation code was accepted
                            content:
                                application/ld+json:
                                    examples:
                            headers: { }
