---
on:
  push:
    branches:
      - 'develop'
name: Build docker image (develop)

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      APP_VERSION: develop
      COMPOSER_ALLOW_SUPERUSER: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build api
      - name: Docker meta (API)
        id: meta-api
        uses: docker/metadata-action@v4
        with:
          images: os2display/os2display-api-service

      - name: Build and push (API)
        uses: docker/build-push-action@v4
        with:
          context: ./infrastructure/display-api-service/
          file: ./infrastructure/display-api-service/Dockerfile
          build-args: |
            VERSION=${{ env.APP_VERSION }}
          push: true
          tags: ${{ steps.meta-api.outputs.tags }}
          labels: ${{ steps.meta-api.outputs.labels }}

      # Build nginx (depends on api build)
      - name: Docker meta (Nginx)
        id: meta-nginx
        uses: docker/metadata-action@v4
        with:
          images: os2display/os2display-api-service-nginx

      - name: Build and push (Nginx)
        uses: docker/build-push-action@v4
        with:
          context: ./infrastructure/nginx/
          file: ./infrastructure/nginx/Dockerfile
          build-args: |
            APP_VERSION=${{ env.APP_VERSION }}
          push: true
          tags: ${{ steps.meta-nginx.outputs.tags }}
          labels: ${{ steps.meta-nginx.outputs.labels }}
